### ISSUE TITLE
Branch Dropdown Doesn't Display Branches

### ISSUE THREAD

**Issue by chrisjlocke** [sqlitebrowser/dbhub.io#104]
Not sure what triggers it, but viewing this link seems to recreate it.
https://db4s-beta.dbhub.io/justinclift/DB4S%20download%20stats.sqlite

The 'Branch' dropdown doesn't display anything.

![image](https://user-images.githubusercontent.com/7872218/30371182-a64ff940-9871-11e7-8be5-a9e1aa20e3f4.png)

Viewing a specific commit (eg, https://db4s-beta.dbhub.io/justinclift/DB4S%20download%20stats.sqlite?branch=master&commit=19328348db45c3cf290132b6f35b9fd6e9d6c23f12292e6b07a8698a5f97146b) does show branches.

![image](https://user-images.githubusercontent.com/7872218/30371225-cf99902c-9871-11e7-90a4-5ada5ec958a3.png)

**Comment by justinclift** [comment]
Ahhh, excellent.  Thanks @chrisjlocke.  I had a ToDo list item to investigate exactly that a while back, but when I went to check it the drop down was fine.

Checking it again now... yep, it's doing it again.  I'll take a look now, while it's acting up. :smile:

**Comment by justinclift** [comment]
Oh... the "viewing a specific commit" just sunk in.  Maybe that's what the problem was last time when I thought it was working.  Will check. :smile:

**Comment by justinclift** [comment]
This one is weird.  **Somehow** branch names are getting duplicated into memcache, which when pulled out and given to the javascript front end leads to the empty drop down.

The duplicated names thing **shouldn't** happen... but obviously is sometimes. :wink:

There's only one code path which sets them... and yep, it's in a loop.  But again, the loop isn't in a way which should do this... but obviously is sometimes. (aargh)

Just added a line of code that *might* fix things, and also added a specific check for this problem so that it logs to the console if/when it happens again. (3441b50db34157b7e233f601666c71a250d3ea14)

Also regenerated the cached page data for this specific page, so that (short term) it'll look like it's working again.  We might need to leave this running for a few weeks though to see if the problem crops up again after entries fall out of cache.

**Comment by justinclift** [comment]
Closing this, as it was fixed a long time ago.
