### ISSUE TITLE
Overwriting / updating database

### ISSUE THREAD

**Issue by rjweise** [sqlitebrowser/dbhub.io#116]
Hey guys, great work so far on the dbhub cloud storage in combination with SQLite database browser. Before I report on my issue, I'll give you some of my setup details:
- Windows 7 enterprise: SQLiteDatabaseBrowserPortable
- Mac OS Mojave: SQLiteDatabaseBrowser Desktop
The creation, manipulation and storing of the database in the cloud was great & easy. My problem is when I start the SQLite Database Browser, open the database from dbhub.io, make edits, write changes and then want to update my database on dbhub.io I get an error message:
![dbhub](https://user-images.githubusercontent.com/10719898/46213488-eafc9d00-c2f5-11e8-8255-ecb8af6191dd.png)
I can write the database to dbhub.io with a new name, but ended up with 20 copies of practically the same database. Not something you would want on your end I assume.
Keep up the great work!
RJ

**Comment by justinclift** [comment]
Ahhhh.  From memory, I **think** that "Upgrade Required" message means it want you to run a newer version of DB4S (note - "DB4S" is our abbreviation for "DB Browser for SQLite" as it gets kind of old typing that full name out each time :wink:).

Try grabbing the latest nightly version, and see if that does it better:

&nbsp; &nbsp; https://nightlies.sqlitebrowser.org/latest/

If that still presents problems, let us know as it's likely something we'll need to fix. :grin:

**Comment by rjweise** [comment]
Is it possible that the portable version is somewhat behind? If not, where would I find the latest version of that (for Windows)? I don't have admin rights so I run the portable version.

**Comment by chrisjlocke** [comment]
Can you install the .MSI on another PC?  If you overwrite the files in the app directory with those from another install, then it'll be 'portable'.  If not, I'll ZIP up an install and send you a link.  I think there are extractors for MSI files, but thats a bit more complex............
PS: 32bit or 64bit?

**Comment by rjweise** [comment]
I don't have another PC, so if you can send a link that's be great. Much appreciated!

**Comment by rjweise** [comment]
uhm, 32 or 64, how do I find out? Oh, got it. 64 please

**Comment by rjweise** [comment]
I looked into it more, and my version (SQLiteDatabaseBrowserPortable_3.10.1_English.paf) is the same as the latest version for Windows 64 bit (DB.Browser.for.SQLite-3.10.1-win64)

**Comment by justinclift** [comment]
No worries.  Over the years, people have occasionally asked for a .zip version of DB4S, exactly for the situation where they don't have admin rights.  We've not gotten around to it, but thinking about it more just now... it could just be a matter of adding an extra command into our install generator.

@karim With the .msi creator, any idea if it's possible to also spit out a .zip at the same time?  Maybe if we can just embed an extra command - either in that or the higher level script that runs it - to run some kind of `zip --recursive "C:\Program Files\DB Browser for SQLite" C:\somedir\outputfile.zip` thing?

**Comment by karim** [comment]
@justinclift Portable version is something I wanted to create but it requires a bit of changes in the code since the application is saving its config in Windows Registry. To get a true portable version the app should save its config in its own directory.

@rjweise Download the latest nightly version and try running this command
`msiexec /a "path\to\installer.msi" /q TARGETDIR=D:\where\to\extract`.

This will extract the content of the .msi file to a folder without requiring admin rights. Inside this folder you will find "DB Browser for SQLite" folder. This is all you need, and you can rename or move the folder anywhere in your system.

**Note:** If the application failed to start because it is missing some system files, move the .dll files inside "System64" folder to "DB Browser for SQLite".

**Comment by justinclift** [comment]
Ahhh, that msiexec command will probably be useful.  We should chuck that on the wiki somewhere, so future potential users can find it.

I wonder how the PortableApp approach gets stuff saved.  Maybe there's some kind of override it's using, which makes stuff get saved to a file instead of in the registry?

**Comment by karim** [comment]
> I wonder how the PortableApp approach gets stuff saved. Maybe there's some kind of override it's using, which makes stuff get saved to a file instead of in the registry?

I think its launcher is monitoring and redirecting registry read/write to a file within the application folder.

For DB4S, we need to change QSettings to save/load the app config to a file instead of letting it pick the default Windows Registry.

**Comment by rjweise** [comment]
Thank you. Unfortunately my work does not allow me to download it, so renaming and installing doesn't seem like a good idea. I appreciate the effort though.
For now renaming the database when saving is not a big issue, just need to make sure I keep deleting previous versions as to not clutter your server.
Cheers!

**Comment by justinclift** [comment]
Just created a new wiki page, with @karim's tip on how to extract the contents of a .msi installer:

&nbsp; &nbsp; https://github.com/sqlitebrowser/sqlitebrowser/wiki/Extracting-installer-contents

Potentially useful for other future people who need to run DB4S on computers without Admin rights. :smile:

**Comment by karim** [comment]
@justinclift I wonder if you could add this command to the build script to extract the .msi then compress the content in a .zip file and put it with the nightlies.

It will not create a truly portable version (since settings are still saved in Windows Registry), but at least it is a start, and users without admin rights can download the .zip file instead of the .msi file.

Also it will let you run different versions of the app side by side, for testing purposes or for fun. :smiley:

**Comment by justinclift** [comment]
Investigating this properly now (finally).  It looks like the problem is that DB4S isn't sending a commit ID when saving subsequent versions, so the server can't sanity check the upload.

@MKleusberg From memory, that's the last outstanding bit needed for server uploads, and er... we haven't gotten around to implementing it yet?

If that's the case, it should be pretty simple to add yeah? :smile:

**Comment by justinclift** [comment]
Also, the weird bug with having to click the OK button twice for uploads is still happening.  It's pretty strange. :wink:

**Comment by MKleusberg** [comment]
@justinclift I think the problem is caused [here](https://github.com/sqlitebrowser/dbhub.io/blob/2aff4eeea1fe71e6b808727e72e57b32e4111992/db4s/main.go#L865). On the client side I get 'https:/db4s.dbhub.io/...' instead of 'https://db4s.dbhub.io/...' which then causes the URLs to not match when trying to find the last commit id for reuploads.

Looking a bit further into this I guess it's because ```filepath.Join``` is removing double '/' from the URL. [Here](https://stackoverflow.com/questions/34668012/combine-url-paths-with-path-join/34668130)'s a Stack Overflow question about it.

**Comment by MKleusberg** [comment]
Cool :+1: Looking forward to see if that's all there is to this issue :smile: 

The OK button issue should be fixed too now. But we should still keep an eye on any timing issues regarding this dialog.

**Comment by justinclift** [comment]
Yep, fixing that line does work. :smile:

Well.. it works for newly uploaded files, then their subsequent uploads/pushes.

It doesn't seem to help for existing files that already exist on the remote server though.  Guessing the incorrect server url is stored in the DB4S metadata?

As a thought, how feasible would it be to check for the problem in the DB4S metadata, and fix the stored incorrect urls?  Just so people don't have to muck around with things on their end (eg delete metadata) to get their existing files working?

---

Think I stumbled over a new bug in the comms too.  When downloading a remote file, trying to re-upload it gives a "Conflict" error.  I'll trace through that one in a bit, to find out what's going on there. :confused:

**Comment by justinclift** [comment]
Gah.  Auto-closing of issues, just when they're mentioned.  Tried to avoid that, didn't work. :wink:

**Comment by justinclift** [comment]
The DB4S end point running on the production server has been updated.

In theory (!) this problem should now be fixed for people.

@rjweise Do you still save stuff to the DBHub.io server?  If so, it should now let you save databases without having to change the name each time.

One minor caveat though, you'll probably need to do one last save with a new name, so it gets "correct" data from the server for subsequent saves.

**Comment by justinclift** [comment]
Closing this, as it's been fixed for ages.
