### ISSUE TITLE
Can't see Views in uploaded database

### ISSUE THREAD

**Issue by bam80** [sqlitebrowser/dbhub.io#125]
Is it implemented already?

**Comment by bam80** [comment]
Sorry I didn't write changes to the db..

**Comment by justinclift** [comment]
No worries.  There's a fair amount of stuff in dbhub.io that's not yet implemented (and will be at some point).  But views should be there. :smile:

**Comment by bam80** [comment]
By the way, will it be possible to not only see the data but also the SQL code?

**Comment by justinclift** [comment]
Which SQL code are you meaning? :smile:

As far as I'm aware, there isn't any stored in SQLite database.  Or are you meaning some form of online editor?

If you're meaning the online editor, then probably not as I think it would be a **huge** amount of work to get right.  Maybe in some distant future point. :wink:

**Comment by bam80** [comment]
I mean at least CREATE statements of tables/views/triggers.
It's stored in the database in `sql` column of respective system tables.

**Comment by justinclift** [comment]
Ahhh.  Interesting idea.  Hadn't thought to include that before, but it should be doable and wouldn't be too hard.

It'll be a few weeks before I switch back to working on dbhub.io stuff.  I can put time into it then. :smile:

**Comment by bam80** [comment]
I think probably we should open separate issue for this, as this one is unrelated.

**Comment by justinclift** [comment]
Good point.  Any interest in opening it? :smile:

**Comment by bam80** [comment]
> Good point. Any interest in opening it?

#126 
> If you're meaning the online editor

Do you know a good one maybe?

**Comment by justinclift** [comment]
> Do you know a good one maybe?

There seem to be several javascript based "online SQL editing" frameworks around.  We use [Redash](https://redash.io) for generating our statistics, and it supports SQLite among many other types of SQL.

We used to have a way of exporting DBHub.io databases online so Redash could use them.  But their import approach changed and we haven't (yet) updated our corresponding piece so that probably doesn't work any more.  If you upload a SQLite database to (say) Dropbox or similar, Redash can probably open it from that. :smile:
