### ISSUE TITLE
Should DB4S end point use http error codes?

### ISSUE THREAD

**Issue by justinclift** [sqlitebrowser/dbhub.io#17]
Looking through the current DB4S end point code, when it encounters an error (eg invalid input, internal server error, etc), it doesn't just returns the error message where JSON output would be expected.  It rarely (eg inconsistently) uses http status codes to indicate there's a problem.

It wouldn't be too hard to change things so that https stats codes are used, but would it be useful? :smile:

**Comment by MKleusberg** [comment]
I think it should, yes. I see three reasons for this:
1) Simplicity. It makes outputting as well as parsing the error message a lot simpler. Assume DB4S is asking for a database that doesn't exist. It's much simpler to just return a 404 error instead of preparing a JSON error object or whatever. Parsing the error makes an even bigger difference.
2) Consistency. We probably want to use http error codes in some places (or even have to for browser compatability etc.). But in this case the best approach seems to be aiming for consistency and using http errors wherever it's possible.
3) Compatability. These error codes are defined in the HTTP standard, so every library or application implementing an HTTP client will understand them. Using the error codes makes it easier for everybody else too. An if somebody asks about our protocol we can just say "HTTPS + some JSON data" instead of having to say "HTTPS except for some parts of it + lots of JSON data".

**Comment by justinclift** [comment]
Cool.  I'll go through the DB4S end point code now and update the appropriate bits. :smile:

**Comment by justinclift** [comment]
Done in 28e678ebd3c12567daf206b9cc3f8cc60283876a.  It turns out there were far fewer places needing updating that expected.
