### ISSUE TITLE
Feature request: Teams

### ISSUE THREAD

**Issue by MKleusberg** [sqlitebrowser/dbhub.io#19]
We probably should add teams (or 'organisations' in Github-speak) sooner than later. First of all because they probably need to be reflected in the basic database schema as well as in many shared Go functions. But also because I've already wanted to test things that currently seem to be impossible because of that (namely forking a private database, that is).

I'd suggest treating teams as normal database user accounts without a password and hence no possibility for login. This way they can be treated as normal users most of the time. What needs to be added though is a way to manage collaborators and to manage (public and private) databases of a different user while taking the access rights into consideration.

**Comment by justinclift** [comment]
Yeah, Teams/Organisations are definitely something we should do.  I'd prefer to leave it until we have some of the other foundation piece in place though, as it (in my head) seems like it would complicate the existing code and SQL queries a whole lot.

**Comment by justinclift** [comment]
As an interesting data point, it turns out we're seeing multiple requests for uploading and downloading databases from multiple IP addresses all using the same client certificate file.

So, looks like people are using that as either a workaround to us not yet having team functionality, or maybe just as a way for individual users to synchronise stuff across multiple machines.

**Comment by MKleusberg** [comment]
Closing this as we have the more active #134 issue for this.
