### ISSUE TITLE
How to debug/trace a failing SQL Query using DB Browser for Windows

### ISSUE THREAD

**Issue by oywino** [sqlitebrowser/dbhub.io#208]
I have an extremely simple test with only two tables where a simple JOIN query produce an incorrect output, but no error message.
What I need is to find out why the query fails to produce the correct output.
It seems to be looping through the tables twice, hence producing a result twice as big as it should be.

Is there a way in DB Browser to debug or trace an SQL query? Or single-stepping it to see exactly what it does?

The query I'm running is this:
SELECT Album.title, Artist.name FROM Album JOIN Artist ON Album.artist_id = artist_id

My tables are these two:
![image](https://github.com/sqlitebrowser/dbhub.io/assets/18447119/bb00b9d7-a478-4bbf-9098-c5ddfb51ad97)

and the output should be:
![image](https://github.com/sqlitebrowser/dbhub.io/assets/18447119/796b5b3a-725c-4ec0-8e42-8c431e7a0dbe)

but instead, this is what I get:
![image](https://github.com/sqlitebrowser/dbhub.io/assets/18447119/53e922a0-9600-4be9-b89f-6a06e0106839)

If I can't figure this one out, I might as well just give up....

**Comment by chrisjlocke** [comment]
There is ```explain``` which details the query plan, but its probably not the 'debug' you're expecting.

The 'gotcha' is specifying the table name on the left side of the join, but not the right.  so instead of ```JOIN Artist ON Album.artist_id = artist_id``` try ```JOIN Artist ON Album.artist_id = artist.artist_id```
Without that, there are indeed two artist fields - one for each table.
In other words, you've got what you asked for. ;)

**Comment by oywino** [comment]
Well thanks for your reply, you were absolutely right! 😊✔👍❤

**Comment by chrisjlocke** [comment]
Thanks for reporting back.

At least it was only a select.  I know 'someone' who did something similar with a delete statement, and wondered where half the database went, instead of just ten records.

![image](https://github.com/sqlitebrowser/dbhub.io/assets/7872218/e73cd18c-2720-46c5-8bd7-33ddd258e4e5)

**Comment by justinclift** [comment]
Closing this, as it seems to have been resolved. :smile:
