### ISSUE TITLE
Can not delete database

### ISSUE THREAD

**Issue by MasterPumpkin** [sqlitebrowser/dbhub.io#223]
Have a nice day,
I can't delete the database. If I click on Delete Database in Settings, it shows Confirm Delete, but the database is still visible in the profile.
If I click on edit database parameters (Public/Private), I get the information that the database file does not exist.
Can you please help me? Thank you very much.

**Comment by justinclift** [comment]
@MasterPumpkin Ahhh.  That pretty clearly sounds like a bug.  I'll have some time to investigate it in a few hours, so will look at it then. :smile:

**Comment by justinclift** [comment]
Instead of waiting a few hours, I've just gone and (manually) deleted it.

I don't yet know *why* the deletion was failing though.  The error message shown on the backend isn't making a lot of sense.

That's something I'll have to investigate properly later.

If you experience the same problem again, please let us know as it's the kind of thing that shouldn't happen at all.

**Comment by MasterPumpkin** [comment]
Thank you very much for your time on this issue :-)  Have a nice day

**Comment by justinclift** [comment]
You're welcome. :smile:
