### ISSUE TITLE
Cannot view second branch

### ISSUE THREAD

**Issue by chrisjlocke** [sqlitebrowser/dbhub.io#72]
I'll try and recreate it (or see if it is) but at the moment, I'm trying to view a branch of a database, but the branch dropdown is displaying the default branch

![image](https://user-images.githubusercontent.com/7872218/29272649-e77b8dde-80f8-11e7-8dbd-3b7b1043f632.png)

I've played with the system, so I'm not too sure if its displaying branch2 but the dropdown is wrong, or its not displaying branch2 at all.... will further test....

**Comment by justinclift** [comment]
Ahhhh, was there a bug that needs fixing?

**Comment by justinclift** [comment]
As a thought, if you go to a database (calling a particular branch like say `?branch=branch2`) then it *should* :wink: display that branch in the view and be the selected one in the dropdown.

After the page loads, if you change to a different branch using the dropdown (eg `branch2` -> `master`) then the URL in the address bar doesn't change to match.  Note - not sure if there's a way to "fix" that apart from reloading the whole page instead of just pulling the updated table info via json.  Maybe something to look at later. :smile:

Anyway, if that's not the sequence you went through to hit this, then there's probably a bug needing fixing. :smile:  If it is though... yeah... not sure how important it is to fix (eg whole page reload) compared to other stuff.

**Comment by chrisjlocke** [comment]
No, I was selecting branch2 in the dropdown, so the URL was updating, but the dropdown wasn't.  
I was clicking on a lot of things though, so its possible I've brokoen something.  It might be linked to one commit I have I can't update... 🐤 ... but as its just one, and I was deleting tags, its probably that.....

**Comment by justinclift** [comment]
You have a commit you can't update?

**Comment by chrisjlocke** [comment]
Indeed.  I think its user error (or twat error, as its me!) If I click 'update' it errors.

![image](https://user-images.githubusercontent.com/7872218/29278653-4fa09d00-810d-11e7-9688-6112acb3cee3.png)

Or if update a tag for that commit

![image](https://user-images.githubusercontent.com/7872218/29278694-6ae8aeae-810d-11e7-893a-6a2acf5efb22.png)

But its only on that commit, so might be something I clicked and upset it.

**Comment by justinclift** [comment]
There is one hole (not of the security type :wink:) in the current approach for updating tags/releases/branches.

When the user clicks the button to Update something (say a tag called `foo`) the following gets sent to the back end server:

* Tag name `foo`
* New tag description content
* If it's a rename, the new tag name too (eg `bar`)

That's then processed server side, so from the server's perspective it's all been done.

I haven't yet figured out how to get the user's browser to understand the tag is now called `bar` though.  So subsequent presses of the Update button by the user on the same page still keep sending the original tag name (`foo`).

Refreshing the page fixes that particular problem, but it's not really a good enough approach medium or longer.  Definitely need to figure out how to tell the page to use the new tag name.

Oh, the same as above applies when renaming branches and releases too.  Cut-n-pasted code for them mostly. :wink:

**Comment by chrisjlocke** [comment]
Can't you send tag IDs?  They'd not change, and that would aid security (?!) - sending a tag ID rather than a name of the tag, which could be very long?

"I've tag 3 here,  Change that to bar".  Javascript would then update the text (or whatever) .... sorry -- thinking out loud!

**Comment by justinclift** [comment]
Oh yeah, that sounds like it'd work.  Cool.

In hindsight it probably should have been obvious.  Doh! :smile:
