### ISSUE TITLE
Pushing a database with multiline commit message results in an error

### ISSUE THREAD

**Issue by chrisjlocke** [sqlitebrowser/dbhub.io#75]
When pushing a database, single line commit messages are fine, but if you enter a carriage return, an error is returned.

![image](https://user-images.githubusercontent.com/7872218/29276994-47ee8392-8108-11e7-8c03-5086f939e62b.png)

This was the dialog as I filled it in

![image](https://user-images.githubusercontent.com/7872218/29276942-23892a84-8108-11e7-8581-a2626adb0b95.png)

**Comment by justinclift** [comment]
Ahhhh, thanks.  This is probably the validation regex not yet understanding newline characters.  Should be easy to fix. :smile:

**Comment by justinclift** [comment]
Looking into this more, it's definitely not a server side regex validation problem.  The https layer in Go is flat out rejecting the http info sent.

At a guess, without (yet) installing Wireshark to see what goes over the wire (could be fun, with this being https and all 👼 ), I'm thinking there's probably some character escaping or url encoding that DB4S needs to do, that's not yet in place.

@MKleusberg Something else interesting with this particular problem.  On this Fedora 25 desktop when this error message comes up in DB4s... clicking on the OK button in the error dialog crashes DB4S.  Probably 80% of the time.

That might actually be good news for chasing things down if it's related to the recent weird upload problem, as I'll probably be able to attach a debugger in Qt Creator and get it to happen there too.

Will attempt it shortly... :smile:

**Comment by justinclift** [comment]
Ugh.  No useful info seems to be in the crash (it's a sigsev).  The stack from main() backwards looks like 100% internal Qt calls. 😦 

![main cpp src sqlitebrowser master - qt creator_007](https://user-images.githubusercontent.com/406299/29294750-daaca7e6-8148-11e7-8b06-e495470bce40.png)

That being said, it's been **ages** (months) since I was doing stuff in Qt Creator/C++.  Might have forgotten something obvious. :smile:

**Comment by justinclift** [comment]
@MKleusberg Hmmm, it might turn out that passing the variable values in the http headers is a bad idea.  We might be better off having them be in the body data or something.  Shouldn't be too hard to implement server side.  Guessing similar DB4S side too?

**Comment by MKleusberg** [comment]
@justinclift Yeah, I've read about multi line fields in HTTP headers in the meantime and there is a workaround but it's been deprecated. I guess that's not too bad because using the HTTP headers for user data seems a bit odd anyway :wink:
Using an extra body part or GET variables should work fine from the DB4S side.

**Comment by justinclift** [comment]
Cool.  I think I went went the header approach first off because I hadn't figured out how to get curl to do them in body data + grab them server side.

I seem to have a bit better understanding of how things work now though, so I can probably figure it out.  I'll attack it again shortly.  Was going to do screenshots for the Chinese lang PR, but I think this is more important and you're going on holiday soon. :smile:

**Comment by justinclift** [comment]
Went with a different approach instead.  DB4S uploads now require POST instead of PUT, and are multi-part form encoded.  Should be a lot more robust (eg encoding of fields)... but I guess we'll find out.

Example working cURL command line:

```
$ curl -kE ~/my.cert.pem -D headers.out -F file=@someupload.sqlite \
    -F "public=true" \
    -F "commitmsg=stuff" \
    -F "sourceurl=https://example.org" \
    -F "licence=CC0" \
    -F "branch=master" https://db4s-beta.dbhub.io:5550/someuser
```

**Comment by chrisjlocke** [comment]
> -F "commitmsg=stuff" \

How are multiline commits handled?  -F "commitmsg=stuff\rsomething\r" \     ;)

**Comment by justinclift** [comment]
I'm optimistically assuming there's some magical encoding of things like that in multi-part form data.

... and yeah, I haven't checked (yet). :smile:

**Comment by justinclift** [comment]
@MKleusberg just committed a change to the DB4S repo so it works with the new POST-only approach.  Seems to handle multi-line commit messages fine too (thank you magical encoding!). 😁

Server side, the webUI isn't displaying the multi-lines on multiple lines though.  I should be able to get that fixed today or tomorrow.

**Comment by justinclift** [comment]
@chrisjlocke The new DB4S nightlies have a fix for the general upload crash problem seen over the last few days, so should be fine for you to test this multi-line problem is fixed now too when you have time/energy. :smile:

**Comment by justinclift** [comment]
@chrisjlocke ping? :smile:

**Comment by chrisjlocke** [comment]
Is there a length limit to commit messages?

![image](https://user-images.githubusercontent.com/7872218/29561740-922e99b6-872e-11e7-90ab-a7db923ddfd3.png)

**Comment by chrisjlocke** [comment]
Yup, 1035 characters.  It might be worth limiting that commit textbox to just 1035 characters?
otherwise, this works grand.  👍 🍇

**Comment by justinclift** [comment]
Ahhh good idea.  Hadn't thought to do that. :smile:

That'll be a thing for @MKleusberg.  I could likely figure it out given some time, but Martin can probably do it in the DB4S dialog box in 5 mins. :smile:

**Comment by justinclift** [comment]
Oh, `1024` btw, not `1035`.  Typo. :wink:

**Comment by chrisjlocke** [comment]
Nope. 1035.  I counted.  Twice.

![image](https://user-images.githubusercontent.com/7872218/29562272-848d6736-8730-11e7-8507-8404344243f6.png)

**Comment by chrisjlocke** [comment]
That might take into account carriage returns and north-polarised catfish though.

**Comment by justinclift** [comment]
Interesting.  The code which assigns the limit is here: https://github.com/sqlitebrowser/dbhub.io/blob/6abd350f3576eb781197f21bed6bf2c21ab714f3/db4s/main.go#L575

This sounds like something to look into, although not urgently.  And yeah, it **might** be something to do white space.  Hopefully it's that simple. :smile:

**Comment by justinclift** [comment]
Looking at your example text above... it seems to have 11 line breaks.

Looking at the difference in the counter in the doc vs the limit... it's 11 off.

I think we can see the source of the problem there. :wink:

**Comment by justinclift** [comment]
At a guess (without checking), I'm thinking each of those line breaks is 2 chars (because Windows).  Which when pasted into DB4S and transmitted over the wire likely become 1 char (because Unix server).

Thus 1035 -> 1024.

That's a working theory though.  If you adjust the # of lines in your example text, then the perceived limit will probably change along with it.

**Comment by justinclift** [comment]
Created a DB4S issue for checking the field limits here: https://github.com/sqlitebrowser/sqlitebrowser/issues/1097

**Comment by chrisjlocke** [comment]
Smartarse. ;)

1024 characters works.  1025 doesn't.

This is one long line of 1024 characters.  Please do not read any further, as it doesn't contain anything interesting.  This is one long line of 1024 characters.  Please do not read any further, as it doesn't contain anything interesting.  This is one long line of 1024 characters.  Please do not read any further, as it doesn't contain anything interesting.  This is one long line of 1024 characters.  Please do not read any further, as it doesn't contain anything interesting.  This is one long line of 1024 characters.  Please do not read any further, as it doesn't contain anything interesting.  This is one long line of 1024 characters.  Please do not read any further, as it doesn't contain anything interesting.  This is one long line of 1024 characters.  Please do not read any further, as it doesn't contain anything interesting.  This is one long line of 1024 characters.  Please do not read any further, as it doesn't contain anything interesting.  This is one long line of 1024 characters.  Please do not read an

**Comment by chrisjlocke** [comment]
Line 575.  So does that error if the lenfgth is over 1024 chars?  Is that the 'bad request' I'm getting back?
(just learning what the flow is)

**Comment by justinclift** [comment]
Yep, that fails and set the "err" variable to a non-nil value, which the next line catches.

That next line sends back http code 400 ("Bad Request") which DB4S catches and doesn't (yet) display meaningful info for. :smile:

**Comment by justinclift** [comment]
As a data point, the entry point of a request from DB4S into the server is here:

https://github.com/sqlitebrowser/dbhub.io/blob/6abd350f3576eb781197f21bed6bf2c21ab714f3/db4s/main.go#L694

It first grabs the username from the client certificate (already validated by the server due to config options), then checks what type of http request was sent.  GET (for info queries), vs POST (for uploads), and calls a function (`getHandler()` or `postHandler()`) for further processing.

If it's useful, I can walk you through it interactively on Gitter or something later?

**Comment by chrisjlocke** [comment]
Excellent, thanks for that.  
Looking at it, either error 413 (payload too large) or 431 (Request Header Fields Too Large) could be used?
I like error 418.... ;)   [](https://tools.ietf.org/html/rfc2324)

**Comment by justinclift** [comment]
Heh Heh Heh

* [431](https://tools.ietf.org/html/rfc6585#section-5) doesn't seem like a good fit, as we're no longer sending the field info in headers.  It gets sent in the main body, encoded a multi-part form data.  When we did used to do that though, then yeah, that might have been the right match.

* [413](https://tools.ietf.org/html/rfc7231#section-6.5.11) sounds workable.  Send a PR? :smile:

On that note... do you have Go and Gogland installed? :smile:

**Comment by justinclift** [comment]
Ahhh, you'll probably want to look over this too for reference:

* https://github.com/golang/go/blob/d6cada7fa4ef92190c2b59c9048413f9280e4a74/src/net/http/status.go#L10-L73
