### ISSUE TITLE
An error occurred when calling errorPage(): memcache: cache miss

### ISSUE THREAD

**Issue by chrisjlocke** [sqlitebrowser/dbhub.io#95]
Sometimes when I visit https://dbhub.io, I get the above error.  A force refresh (Ctrl+F5) doesn't resolve the issue.  Clearing the cookies does.

I assume its the 'guts in the background' have changed, so the 'state' or 'page' the cookie is sending me isn't valid anymore?

I think its in your 'to do' list, but wasn't sure if it was explicitly this error (ie, when visiting the site).

Also, making an 'official' note of it, in case someone else gets the error, so they know its being looked into...

PS: I'm on Chrome x64, v60, if that makes any difference.

**Comment by justinclift** [comment]
Ahhhhhh.  I thought I was the only one getting that, due to swapping between my dev and test env.

Thanks for reporting it.  It means other people are likely hitting it as well, which isn't good.

I have an idea with what's causing it, but yeah it's buried right down in the guts of one of the libraries we're using.  Still, it should be fixable and the author is friendly. :smile:

**Comment by justinclift** [comment]
This should be fixed now, in 9dcc844c2bde028a8a4e578d4d9c526a1ac39010.

I've tested it every way I can think of on my local dev box, and stale sessions (the source of `memcache: cache miss`) are now detected and deleted before proceeding.

**Comment by justinclift** [comment]
@chrisjlocke Has this error happened to you since?  It hasn't happened for me, so I'm thinking it's solved now. :smile:

**Comment by chrisjlocke** [comment]
Closing due to lack of response.
No, er, I mean, due to the Happy Coder.

**Comment by justinclift** [comment]
Thanks @chrisjlocke. :smile:
